# Generated by Django 5.1 on 2026-04-20 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pollution", "0002_pollutiondata_pm25_alter_pollutiondata_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pollutiondata",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
